# Generated by Django 5.0.3 on 2024-03-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='phone',
        ),
    ]
