# Generated by Django 5.0.3 on 2024-06-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_addressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='ostan',
            field=models.CharField(max_length=100, null=True, verbose_name='ostan'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='address'),
        ),
    ]
