# Generated by Django 5.0.3 on 2024-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_addressmodel_city_addressmodel_ostan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='text',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
