# Generated by Django 5.0.3 on 2024-06-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0005_addressmodel_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressmodel',
            old_name='text',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='addressmodel',
            old_name='ostan',
            new_name='state',
        ),
    ]
