# Generated by Django 5.0.3 on 2024-07-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0006_rename_text_addressmodel_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیر فعال'),
        ),
    ]
