# Generated by Django 5.0.3 on 2024-03-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product/')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس محصولات',
            },
        ),
        migrations.CreateModel(
            name='CatgoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.catgorymodel', verbose_name='')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('writer', models.CharField(max_length=100, verbose_name='')),
                ('translator', models.CharField(max_length=100, null=True, verbose_name='')),
                ('price', models.IntegerField(verbose_name='')),
                ('page', models.IntegerField(verbose_name='')),
                ('publisher', models.CharField(max_length=100, verbose_name='')),
                ('detail', models.TextField(verbose_name='')),
                ('is_active', models.BooleanField(verbose_name='')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='')),
                ('catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.catgorymodel', verbose_name='')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productimagemodel', verbose_name='')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
