# Generated by Django 5.0.3 on 2024-03-30 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='عنوان در مرورگر')),
            ],
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='translator',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='writer',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cover',
            field=models.CharField(max_length=100, null=True, verbose_name='جلد'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cut',
            field=models.CharField(max_length=100, null=True, verbose_name='قطع'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='field',
            field=models.CharField(max_length=100, null=True, verbose_name='رشته'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='grade',
            field=models.CharField(max_length=100, null=True, verbose_name='پایه'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='lesson',
            field=models.CharField(max_length=100, null=True, verbose_name='درس'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='publish_date',
            field=models.IntegerField(null=True, verbose_name='سال انتشار'),
        ),
        migrations.AlterField(
            model_name='catgorymodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته'),
        ),
        migrations.AlterField(
            model_name='catgorymodel',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.catgorymodel', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='catgorymodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='عنوان در مرورگر'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='img',
            field=models.ImageField(upload_to='product/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='catgory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.catgorymodel', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='detail',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productimagemodel', verbose_name='عکس ها'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='page',
            field=models.IntegerField(verbose_name='صفحه'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='عنوان در مرورگر'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.publishermodel', verbose_name='انتشارات'),
        ),
    ]
