# Generated by Django 5.0.3 on 2024-03-30 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_publishermodel_remove_productmodel_translator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishermodel',
            options={'verbose_name': 'ناشر', 'verbose_name_plural': 'انتشارات'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='img',
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productmodel', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='catgorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.catgorymodel', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.publishermodel', verbose_name='فروشنده'),
        ),
    ]
