# Generated by Django 5.0.3 on 2024-03-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_publishermodel_options_remove_productmodel_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='cover',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جلد'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='cut',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قطع'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='lesson',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='publish_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال انتشار'),
        ),
    ]
