# Generated by Django 5.0.3 on 2024-03-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_productmodel_cover_alter_productmodel_cut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='تخفیف'),
        ),
    ]
