# Generated by Django 5.0.3 on 2024-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='نظرات'),
        ),
    ]
