# Generated by Django 5.0.3 on 2024-03-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='count',
            field=models.IntegerField(null=True, verbose_name='نعداد'),
        ),
    ]
