# Generated by Django 5.0.3 on 2024-04-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_alter_commentmodel_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
