# Generated by Django 5.0.3 on 2024-04-08 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_alter_commentmodel_options_commentmodel_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='rating',
            field=models.IntegerField(editable=False, null=True, verbose_name='نظرات'),
        ),
        migrations.CreateModel(
            name='CatgoryImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product/', verbose_name='عکس')),
                ('catgory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.catgorymodel', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'عکس دسته',
                'verbose_name_plural': 'عکس دسته بندی',
            },
        ),
    ]
