# Generated by Django 5.0.3 on 2024-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_alter_productmodel_rating_catgoryimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='تخفیف ویژه فعال / غیر فعال'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='special_discount_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تخفیف'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='تخفیف'),
        ),
    ]
