# Generated by Django 5.0.3 on 2024-07-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_productmodel_is_special_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='special_discount_date',
            field=models.DateField(blank=True, null=True, verbose_name='زمان تخفیف'),
        ),
    ]
