# Generated by Django 5.0.3 on 2024-07-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_alter_productmodel_special_discount_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='catgory',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='catgory',
            field=models.ManyToManyField(to='product_module.catgorymodel', verbose_name='دسته بندی'),
        ),
    ]
