# Generated by Django 5.0.3 on 2024-07-02 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_productslidermodel_favriteproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavriteProduct',
            new_name='FavoriteProduct',
        ),
    ]
