# Generated by Django 5.0.3 on 2024-07-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_rename_favriteproduct_favoriteproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'verbose_name': 'محصول مورد علاقه', 'verbose_name_plural': 'محصولات مورد علاقه'},
        ),
        migrations.AlterModelOptions(
            name='productslidermodel',
            options={'verbose_name': 'اسلاید', 'verbose_name_plural': 'اسلاید ها'},
        ),
    ]
