# Generated by Django 5.1.4 on 2024-12-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_token_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
