# Generated by Django 5.1.4 on 2024-12-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_address_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
