# Generated by Django 5.0.3 on 2024-04-21 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_module', '0012_alter_productmodel_rating_catgoryimagemodel'),
        ('user_module', '0003_addressmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pay', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('pay_datetime', models.DateField(null=True, verbose_name='زمان پرداخت')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.addressmodel', verbose_name='آدرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(verbose_name='قیمت نهایی')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productmodel', verbose_name='محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_module.ordermodel', verbose_name='سبد خرید')),
            ],
        ),
    ]
