# Generated by Django 5.0.3 on 2024-05-31 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
        ('user_module', '0003_addressmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_module.addressmodel', verbose_name='آدرس'),
        ),
    ]
