# Generated by Django 5.0.3 on 2024-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_alter_ordermodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delevery_type',
            field=models.CharField(max_length=100, null=True, verbose_name='نوع ارسال'),
        ),
    ]
