# Generated by Django 5.0.3 on 2024-06-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_ordermodel_delevery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='delevery_type',
            new_name='delivery_type',
        ),
    ]
