# Generated by Django 5.0.3 on 2024-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_rename_delevery_type_ordermodel_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_price',
            field=models.IntegerField(null=True, verbose_name='قیمت ارسال'),
        ),
    ]
