# Generated by Django 5.0.3 on 2024-06-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_ordermodel_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery_price',
            field=models.IntegerField(default=10000, null=True, verbose_name='قیمت ارسال'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery_type',
            field=models.CharField(default='normal', max_length=100, null=True, verbose_name='نوع ارسال'),
        ),
    ]
