# Generated by Django 5.0.3 on 2024-07-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_alter_ordermodel_delivery_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='کد')),
                ('discount', models.IntegerField(verbose_name='تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_module.discountcodemodel', verbose_name='کد تخفیف'),
        ),
    ]
