# Generated by Django 5.0.3 on 2024-07-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0007_discountcodemodel_ordermodel_discount_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcodemodel',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد های تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='orderdetailmodel',
            options={'verbose_name': 'محصول سبد خرید', 'verbose_name_plural': 'محصول های سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
    ]
