# Generated by Django 5.1.4 on 2025-05-19 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_discountcode_cart_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='carts.discountcode'),
        ),
    ]
