# Generated by Django 5.1.4 on 2025-05-20 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_is_paid'),
        ('users', '0004_remove_address_token_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.address'),
        ),
    ]
