# Generated by Django 5.1.4 on 2025-05-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.BooleanField(default=False),
        ),
    ]
