# Generated by Django 5.1.4 on 2025-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
