# Generated by Django 5.1.4 on 2025-01-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfeatures',
            old_name='features_description',
            new_name='feature_description',
        ),
        migrations.RenameField(
            model_name='productfeatures',
            old_name='features_title',
            new_name='feature_title',
        ),
    ]
