# Generated by Django 5.1.4 on 2025-05-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
    ]
