# Generated by Django 5.1.4 on 2025-05-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_productfeatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_title',
            new_name='category_title',
        ),
    ]
