# Generated by Django 5.1.4 on 2025-05-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_discountedproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_precentage',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DiscountedProduct',
        ),
    ]
