# Generated by Django 5.1.4 on 2025-05-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_discounted_precentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_precentage',
            new_name='discounted_percentage',
        ),
    ]
