# Generated by Django 5.1.4 on 2025-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_discounted_precentage_product_discounted_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
