# Generated by Django 5.1.4 on 2025-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_discounted_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
