# Generated by Django 5.1.4 on 2025-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_discounted_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book_translator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
